### ISSUE TITLE
An Experimental Analysis of Indoor Spatial Queries: Modeling, Indexing, and Processing

### ISSUE THREAD

**Issue by liuchunhui-sunlight** [indoorLBS/ISQEA#3]
pom.xml文件没找到，运行时有的包找不到；另外因为之前没接触过Java，想问一个基础的问题这是IDEA下的Maven项目吗，需要下载别的什么吗？之前论文您们的实验环境系统是Mac系统，windows系统可以吗？希望能得到您的回复

**Comment by longaspire** [comment]
本项目为Java项目，未配置Maven依赖，故无pom.xml文件。可以导入IDEA运行及修改，Java跨平台环境可在Mac、Win及Linux下进行开发。

**Comment by liuchunhui-sunlight** [comment]
好的，非常感谢您在百忙之中给予回复，对我的帮助很大，非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "indoorLBS/ISQEA"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月24日(星期三) 晚上9:26
收件人:&nbsp;"indoorLBS/ISQEA"<ISQEA@noreply.github.com&gt;;
抄送:&nbsp;"sunny"<3065783089@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [indoorLBS/ISQEA] An Experimental Analysis of Indoor Spatial Queries: Modeling, Indexing, and Processing (#3)





 
本项目为Java项目，未配置Maven依赖，故无pom.xml文件。可以导入IDEA运行及修改，Java跨平台环境可在Mac、Win及Linux下进行开发。

**Comment by liuchunhui-sunlight** [comment]
Dear author:

      Hello! There is RX package in the code of your paper. I checked the rack package that should be imported into rxjava on the Internet. I don't know whether you use rxjava1 or rxjava2 in your code. I hope I can get your answer.Thank you very much
